name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9','3.10','3.11','3.12','3.13']

    steps:
      - uses: actions/checkout@v4

      # Install uv and select the Python for this job
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      # Create a project-local virtual environment (.venv)
      - name: Create venv
        run: uv venv

      # Install your package + test extras
      - name: Install dependencies
        run: uv pip install -e ".[test]"

      # Run tests inside the uv-managed venv
      - name: Run pytest
        run: uv run pytest -q
